=== albertoGF-dawt/ejs-de-xml-Alberto/unxsd/dtdej.dtd
<!ELEMENT library (book+)>
<!ATTLIST library xmlns:xsi CDATA #REQUIRED>
<!ATTLIST library xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT book (title, price, publisher?, editorial?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!ELEMENT publisher (name, country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT editorial (name, country)>

<!ATTLIST book isbn CDATA #REQUIRED>
<!ATTLIST book category CDATA #IMPLIED>

=== albertoGF-dawt/ejs-de-xml-Alberto/unxsd/xmlej.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "dtdej.dtd">

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsdej.xsd">
    <!-- <library> -->

    <book isbn="123A" category="fiction">
        <title>XML Basics</title>
        <price>25.5</price>

        <publisher>
            <name>TechBooks</name>
            <country>Spain</country>
        </publisher>
    </book>

    <book isbn="456B" category="science">
        <title>Advanced XML</title>
        <price>40</price>
        <!-- AQUÍ USAMOS substitutionGroup -->
        <editorial>
            <name>SciencePress</name>
            <country>Germany</country>
        </editorial>
    </book>

</library>
